# Generated by Django 3.2.25 on 2024-08-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Email',
        ),
        migrations.AlterField(
            model_name='student',
            name='Age',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='Year',
            field=models.CharField(max_length=50),
        ),
    ]
