# Generated by Django 5.1 on 2024-08-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=15)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
