# Generated by Django 5.1 on 2024-08-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_enquiry_email_alter_enquiry_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='id',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
